-- Fleet Health: aggregates the IoT/edge sensor diagnostics AttendanceView
-- already computes locally on every device (see components/
-- EdgeDiagnosticsPanel.jsx) into a supervisor-facing view of the whole
-- fleet, not just one person's own session. Previously every one of these
-- signals (inference latency, model tier, lens clarity, network/battery
-- state) was purely local -- genuinely useful individually, but nobody
-- with a fleet of devices could see "are several devices struggling",
-- "is a particular network condition common", etc.
-- Prerequisite: 20260712_add_rls_policies.sql (uses its is_supervisor()).

create table if not exists public.device_health_snapshots (
    id bigint generated by default as identity primary key,
    employee_id uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now(),
    avg_latency_ms integer,
    model_tier text check (model_tier in ('full', 'reduced')),
    network_effective_type text,
    is_slow_network boolean,
    battery_level numeric,
    is_charging boolean,
    lens_clear boolean,
    motion_stable boolean,
    ambient_lux numeric
);

create index if not exists device_health_snapshots_created_at_idx on public.device_health_snapshots (created_at desc);

alter table public.device_health_snapshots enable row level security;

-- Employees can only ever report THEIR OWN snapshot (employee_id must
-- match their own auth.uid()) -- prevents one user from forging telemetry
-- attributed to someone else.
drop policy if exists device_health_snapshots_insert_own on public.device_health_snapshots;
create policy device_health_snapshots_insert_own
  on public.device_health_snapshots
  for insert
  with check (auth.uid() = employee_id);

drop policy if exists device_health_snapshots_select_supervisor_only on public.device_health_snapshots;
create policy device_health_snapshots_select_supervisor_only
  on public.device_health_snapshots
  for select
  using (public.is_supervisor());
