-- ============================================================================
-- DEBUG CENTER: DIAGNOSTIC HISTORY + AUTO-ALERT ON A CRITICAL FAILURE
-- ============================================================================
-- Every time a supervisor runs the Connectivity checks in Debug Center, the
-- result is persisted here -- turns "is it down right now?" into "has it
-- been flaky?" (a snapshot vs. a trend). Also drives an automatic
-- supervisor-wide notification the first time the Hugging Face CDN check
-- (the exact, previously-invisible failure mode that broke Attendance's
-- face recognition) fails, instead of requiring someone to notice it in
-- the UI. Rate-limited to one alert per 6 hours so a supervisor manually
-- re-running checks against a genuinely down CDN doesn't spam every other
-- supervisor's notification tray.

create table if not exists public.debug_diagnostic_runs (
  id bigint generated by default as identity primary key,
  supervisor_id uuid not null references public.profiles(id) on delete cascade,
  results jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists debug_diagnostic_runs_created_idx on public.debug_diagnostic_runs (created_at desc);

alter table public.debug_diagnostic_runs enable row level security;

drop policy if exists debug_diagnostic_runs_select_supervisor on public.debug_diagnostic_runs;
create policy debug_diagnostic_runs_select_supervisor
  on public.debug_diagnostic_runs
  for select
  using (public.is_supervisor());

drop policy if exists debug_diagnostic_runs_insert_own on public.debug_diagnostic_runs;
create policy debug_diagnostic_runs_insert_own
  on public.debug_diagnostic_runs
  for insert
  with check (supervisor_id = auth.uid() and public.is_supervisor());

create or replace function public.trg_alert_on_critical_diagnostic_failure()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recent_alert_count int;
  v_supervisor record;
begin
  -- Only the Hugging Face CDN (YOLO face-model host) check triggers an
  -- alert -- the one failure mode that's silent everywhere else in the
  -- app (a generic Supabase-unreachable failure wouldn't even let this
  -- insert happen, and every other check here is advisory, not
  -- app-breaking).
  if exists (
    select 1 from jsonb_array_elements(new.results) as check_result
    where check_result->>'label' = 'huggingface-cdn' and (check_result->>'ok')::boolean = false
  ) then
    select count(*) into v_recent_alert_count
    from public.notifications
    where message like 'Diagnostic alert:%Hugging Face%'
      and created_at > now() - interval '6 hours';

    if v_recent_alert_count = 0 then
      for v_supervisor in select id from public.profiles where role = 'supervisor' loop
        perform public.notify(
          v_supervisor.id,
          'Diagnostic alert: Hugging Face CDN (face-recognition model host) is unreachable from a recent Debug Center check -- this can silently break face detection on Attendance without any other error showing.'
        );
      end loop;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists alert_on_critical_diagnostic_failure on public.debug_diagnostic_runs;
create trigger alert_on_critical_diagnostic_failure
  after insert on public.debug_diagnostic_runs
  for each row execute function public.trg_alert_on_critical_diagnostic_failure();
