-- Documents the audit_log system already live in the database (table +
-- log_audit_event() + 4 triggers on leave_requests/performance_evaluations/
-- profiles/tasks) -- discovered to exist in production but was never
-- captured in any migration file, meaning a fresh project restored purely
-- from this migrations/ folder would silently be missing it entirely.
-- Every statement here is written to be a safe no-op against a database
-- where this already exists (create table if not exists, create or
-- replace function, drop policy if exists + create) as well as a correct
-- from-scratch setup on a fresh project.
-- Prerequisite: 20260712_add_rls_policies.sql (uses its is_supervisor()).

create table if not exists public.audit_log (
    id bigint generated by default as identity primary key,
    actor_id uuid references auth.users(id) on delete set null,
    action text not null,
    entity_type text not null,
    entity_id text,
    details jsonb,
    created_at timestamptz not null default now()
);

alter table public.audit_log enable row level security;

drop policy if exists audit_log_select_supervisor_only on public.audit_log;
create policy audit_log_select_supervisor_only
  on public.audit_log
  for select
  using (public.is_supervisor());

-- Shared write path every audit trigger below calls through -- keeps the
-- insert shape (actor always auth.uid(), never client-supplied) in one
-- place. security definer + a fixed search_path so it can insert
-- regardless of the calling row's own RLS context.
create or replace function public.log_audit_event(p_action text, p_entity_type text, p_entity_id text, p_details jsonb)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.audit_log (actor_id, action, entity_type, entity_id, details)
  values (auth.uid(), p_action, p_entity_type, p_entity_id, p_details);
$$;

-- --- leave_requests: approve/reject/cancel ---
create or replace function public.trg_audit_leave_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and new.status is distinct from old.status then
    perform public.log_audit_event(
      'status_change', 'leave_request', new.id::text,
      jsonb_build_object('type', new.type, 'from', old.status, 'to', new.status)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists audit_leave_status_change on public.leave_requests;
create trigger audit_leave_status_change
  after update on public.leave_requests
  for each row execute function public.trg_audit_leave_status_change();

-- --- performance_evaluations: created/updated/deleted ---
create or replace function public.trg_audit_evaluation_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.log_audit_event(
      'created', 'performance_evaluation', new.id::text,
      jsonb_build_object('employee_id', new.employee_id, 'final_score', new.final_score)
    );
  elsif tg_op = 'UPDATE' then
    perform public.log_audit_event(
      'updated', 'performance_evaluation', new.id::text,
      jsonb_build_object('employee_id', new.employee_id, 'from_score', old.final_score, 'to_score', new.final_score)
    );
  elsif tg_op = 'DELETE' then
    perform public.log_audit_event(
      'deleted', 'performance_evaluation', old.id::text,
      jsonb_build_object('employee_id', old.employee_id, 'final_score', old.final_score)
    );
  end if;
  return coalesce(new, old);
end;
$$;

drop trigger if exists audit_evaluation_change on public.performance_evaluations;
create trigger audit_evaluation_change
  after insert or update or delete on public.performance_evaluations
  for each row execute function public.trg_audit_evaluation_change();

-- --- profiles: role changes ---
create or replace function public.trg_audit_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and new.role is distinct from old.role then
    perform public.log_audit_event(
      'role_change', 'profile', new.id::text,
      jsonb_build_object('name', new.name, 'from', old.role, 'to', new.role)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists audit_role_change on public.profiles;
create trigger audit_role_change
  after update on public.profiles
  for each row execute function public.trg_audit_role_change();

-- --- tasks: status changes (approve/reject/complete/etc.) ---
create or replace function public.trg_audit_task_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and new.status is distinct from old.status then
    perform public.log_audit_event(
      'status_change', 'task', new.id::text,
      jsonb_build_object('title', new.title, 'from', old.status, 'to', new.status)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists audit_task_status_change on public.tasks;
create trigger audit_task_status_change
  after update on public.tasks
  for each row execute function public.trg_audit_task_status_change();
